services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_user -d keycloak_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  openldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: BionicPRO
      LDAP_DOMAIN: example.com
      LDAP_ADMIN_PASSWORD: admin
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
    volumes:
      - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
    ports:
      - "389:389"

  keycloak:
    image: quay.io/keycloak/keycloak:26.7
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME: "http://localhost:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      keycloak_db:
        condition: service_healthy
      openldap:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/8080' >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20

  bionicpro-auth:
    build:
      context: ./bionicpro-auth
    environment:
      KEYCLOAK_PUBLIC_URL: http://localhost:8080
      KEYCLOAK_INTERNAL_URL: http://keycloak:8080
      KEYCLOAK_REALM: reports-realm
      KEYCLOAK_CLIENT_ID: bionicpro-auth
      KEYCLOAK_CLIENT_SECRET: bionicpro-auth-local-secret
      AUTH_FERNET_KEY: D-eX02wALHUJeFP2nvrtjjDBCgYfiQDK98NoKQouwbI=
      FRONTEND_URL: http://localhost:3000
      REDIRECT_URI: http://localhost:8000/auth/callback
    volumes:
      - ./bionicpro-auth/app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      keycloak:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      REACT_APP_AUTH_URL: http://localhost:8000

volumes:
  keycloak_db_data:
  frontend_node_modules:
